### ISSUE TITLE
Route Auth

### ISSUE THREAD

**Issue by Oliviera1994** [DeFiChange/api-fiat2defi#24]
Route: /v1/auth
Authorisierung: Legacy Adresse + Signatur im Auth Header (Basic Auth)
Type: GET
Body: -
Query Parameter: -

Response JWT Token

**Comment by phil-schoe** [comment]
Wenn wir über JWT authorisieren, würde ich einen POST auf die auth Route machen und die Daten im Body übergeben. Für die späteren Routen den Token dann im Header als "Bearer Token".
Passt das für euch?

**Comment by phil-schoe** [comment]
Done
