### ISSUE TITLE
Route Asset

### ISSUE THREAD

**Issue by Oliviera1994** [DeFiChange/api-fiat2defi#6]
- [x] Gebe alle assets zurück

      Route: /v1/asset
      Authorisierung: -
      Type: GET
      Body: -
      Query Parameter: -

- [x] Gebe ausgewähltes asset zurück

      Route: /v1/asset/<key> -> key kann beispielsweise 0 oder DFI
      Authorisierung: -
      Type: GET
      Body: -
      Query Parameter: -

- [x] Lege neues asset an

      Route: /v1/asset
      Authorisierung: oAuth im Header -> abgleich mit Admin Token in der DB
      Type: POST
      Body: 
      {
      "id": "24",
      "name": "DFI",
      "type": "Coin",
      "buyable": "1",
      "sellable": "1"
      }
      Query Parameter: -

- [x] Asset ändern
  
       Route: /v1/asset/<key>
       Authorisierung: oAuth im Header -> abgleich mit Admin Token in der DB
       Type: PUT
       Body: 
       {
       "buyable": true,
       "sellable": true
       }
       Query Parameter: -

**Comment by Kolibri1990** [comment]
Done
